[run]
init_cmds = [
	["go", "build", "-o", "build/mread"],
	["./build/mread"]
]
watch_all = true
watch_dirs = ["views"]
watch_exts = [".go", ".amber"]
ignore = [".git", "node_modules"]
ignore_files = []
build_delay = 1000
interrupt_timout = 15
graceful_kill = false
cmds = [
	["go", "build", "-o", "build/mread"],
	["./build/mread"]
]
